### PR TITLE
Fix resize and condition when empty

### LINKED ISSUE #448: FIX UI - hauteur des pubs

### PR DESCRIPTION
**Pull request by KevynSola**
Closes #448 , #449 , #450

### CODE REVIEW

**Review by lucianpurcaru — APPROVED** [review]

File: src/Controller/VideoController.php [hunk 1]
```diff
@@ -29,8 +29,11 @@ public function showVideo(
         AdvertRepository $advertRepository
     ): Response {
         $ads = $advertRepository->findAll();
-        $randAds = $ads[array_rand($ads, 1)];
-
+        if ($ads != null) {
```
Comment (sblondeau) [inline src/Controller/VideoController.php:32]: !==

File: templates/video/index.html.twig [hunk 2]
```diff
@@ -77,14 +77,16 @@
 			</div>
 		</div>
 		<div class="container-fluid p-0 mt-5">
-			<div class="bloc-ads mb-4">
-				<div class="string-ad bg-light">
-					<p class="text-center text-dark mb-0">Publicité</p>
+			{% if ads != null %}
```
Comment (sblondeau) [inline templates/video/index.html.twig:80]: if ads is not null

**Review by sblondeau — CHANGES_REQUESTED** [review]

**Review by shvilaine — APPROVED** [review]

**Review by sblondeau — APPROVED** [review]
